# Generated by Django 4.0.6 on 2022-07-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='_post_raing',
            new_name='_post_rating',
        ),
    ]
