# Generated by Django 4.0.6 on 2022-07-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_rename__post_raing_post__post_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='_post_rating',
            field=models.IntegerField(default=0),
        ),
    ]
