# Generated by Django 4.0.6 on 2022-07-08 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_alter_post__post_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user_rating',
            field=models.FloatField(db_column='rating', default=0.0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(db_column='name', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='_comment_rating',
            field=models.IntegerField(db_column='rating', default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, db_column='date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(db_column='text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='_post_rating',
            field=models.IntegerField(db_column='rating', default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_author',
            field=models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.CASCADE, to='News.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ManyToManyField(db_column='category', through='News.PostCategory', to='News.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(auto_now_add=True, db_column='date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_header',
            field=models.CharField(db_column='header', max_length=125),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(db_column='text'),
        ),
    ]
