# Generated by Django 4.0.6 on 2022-07-15 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_alter_author_user_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_header',
        ),
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(db_column='header', default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author',
            name='user_rating',
            field=models.SmallIntegerField(db_column='rating', default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='News.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='_post_rating',
            field=models.SmallIntegerField(db_column='rating', default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_author',
            field=models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='News.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NE', 'Новости'), ('AR', 'Статья')], default='NE', max_length=2),
        ),
    ]
