# Generated by Django 3.2.13 on 2022-07-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_remove_post_post_header_post_post_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(db_column='category', through='News.PostCategory', to='News.Category'),
        ),
    ]
