# Generated by Django 4.0.6 on 2022-08-09 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_auto_20220716_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySubcribes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(db_column='category', through='News.CategorySubcribes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorysubcribes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.category'),
        ),
        migrations.AddField(
            model_name='categorysubcribes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
