# Generated by Django 4.0.6 on 2022-08-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_alter_post__post_rating_alter_post_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
