# Generated by Django 4.0.6 on 2022-10-14 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0013_alter_comment_options_alter_comment__comment_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en_us',
            field=models.CharField(db_column='name_en_us', help_text='введите название категории', max_length=64, null=True, unique=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(db_column='name_ru', help_text='введите название категории', max_length=64, null=True, unique=True, verbose_name='Category name'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_en_us',
            field=models.TextField(db_column='text_en_us', help_text='введите текст поста', null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_ru',
            field=models.TextField(db_column='text_ru', help_text='введите текст поста', null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(db_column='header_en_us', default='', help_text='введите заголовок поста', max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(db_column='header_ru', default='', help_text='введите заголовок поста', max_length=128, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='type_en_us',
            field=models.CharField(choices=[('NE', 'Новости'), ('AR', 'Статья')], default='NE', help_text='выберите тип поста', max_length=2, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='post',
            name='type_ru',
            field=models.CharField(choices=[('NE', 'Новости'), ('AR', 'Статья')], default='NE', help_text='выберите тип поста', max_length=2, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(help_text='выберите имя поьзователя из списка', on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='User name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user_rating',
            field=models.SmallIntegerField(db_column='rating', default=0, help_text='введите рейтиг пользователя', verbose_name='User rating'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(db_column='name', help_text='введите название категории', max_length=64, unique=True, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='_comment_rating',
            field=models.IntegerField(db_column='rating', default=0, help_text='укажите рейтинг комментария', verbose_name='Comment rating'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, db_column='date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(db_column='text', help_text='введите комментарий к посту', verbose_name='Comment on post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(help_text='выберите пост', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='News.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='выберите пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='_post_rating',
            field=models.SmallIntegerField(db_column='rating', default=0, help_text='укажите рейтинг поста', verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(db_column='author', help_text='выберите автора', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='News.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(db_column='category', through='News.PostCategory', to='News.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True, db_column='date', help_text='укажите дату публикации поста', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(db_column='text', help_text='введите текст поста', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_column='header', default='', help_text='введите заголовок поста', max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('NE', 'Новости'), ('AR', 'Статья')], default='NE', help_text='выберите тип поста', max_length=2, verbose_name='Type'),
        ),
    ]
